//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Catalog_Studentesc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOG_TEMPORAR
    {
        public int MaterieID { get; set; }
        public string NumeMaterie { get; set; }
        public int Profesor1ID { get; set; }
        public Nullable<int> Profesor2ID { get; set; }
        public int Asistent1ID { get; set; }
        public Nullable<int> Asisten2ID { get; set; }
        public Nullable<float> ProcentCurs { get; set; }
        public Nullable<float> ProcentLaborator { get; set; }
        public Nullable<float> ProcentTeme { get; set; }
        public Nullable<float> ProcentProiect { get; set; }
        public Nullable<bool> Examen { get; set; }
        public Nullable<int> Credite { get; set; }
    }
}
