//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Catalog_Studentesc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facultate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facultate()
        {
            this.Departamnets = new HashSet<Departamnet>();
        }
    
        public int FacultateID { get; set; }
        public string Nume_Intreg { get; set; }
        public string Prescurtare { get; set; }
        public Nullable<int> DecanID { get; set; }
        public Nullable<int> AdministratorFacultate1ID { get; set; }
        public Nullable<int> AdministratorFacultate2ID { get; set; }
    
        public virtual Cadru Cadru { get; set; }
        public virtual Cadru Cadru1 { get; set; }
        public virtual Cadru Cadru2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamnet> Departamnets { get; set; }
    }
}
