//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Catalog_Studentesc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupa()
        {
            this.Materies = new HashSet<Materie>();
            this.StudentiGrupas = new HashSet<StudentiGrupa>();
        }
    
        public int GrupaID { get; set; }
        public string Nume { get; set; }
        public int An { get; set; }
        public int AnScolarID { get; set; }
        public int SpecializareID { get; set; }
    
        public virtual AnScolar AnScolar { get; set; }
        public virtual Specializare Specializare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materie> Materies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentiGrupa> StudentiGrupas { get; set; }
    }
}
