//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Catalog_Studentesc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materie()
        {
            this.Notas = new HashSet<Nota>();
        }
    
        public int MaterieID { get; set; }
        public int GrupaID { get; set; }
        public string NumeMaterie { get; set; }
        public int Profesor1ID { get; set; }
        public Nullable<int> Profesor2ID { get; set; }
        public int Asistent1ID { get; set; }
        public Nullable<int> Asisten2ID { get; set; }
        public float ProcentCurs { get; set; }
        public Nullable<float> ProcentLaborator { get; set; }
        public Nullable<float> ProcentTeme { get; set; }
        public Nullable<float> ProcentProiect { get; set; }
        public bool Examen { get; set; }
        public Nullable<int> Credite { get; set; }
        public Nullable<int> Sesiune { get; set; }
    
        public virtual Cadru Cadru { get; set; }
        public virtual Cadru Cadru1 { get; set; }
        public virtual Cadru Cadru2 { get; set; }
        public virtual Cadru Cadru3 { get; set; }
        public virtual Grupa Grupa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Notas { get; set; }
    }
}
