//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Catalog_Studentesc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CatalogEntities1 : DbContext
    {
        public CatalogEntities1()
            : base("name=CatalogEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnScolar> AnScolars { get; set; }
        public virtual DbSet<Cadru> Cadrus { get; set; }
        public virtual DbSet<Departamnet> Departamnets { get; set; }
        public virtual DbSet<Facultate> Facultates { get; set; }
        public virtual DbSet<Grupa> Grupas { get; set; }
        public virtual DbSet<Materie> Materies { get; set; }
        public virtual DbSet<Nota> Notas { get; set; }
        public virtual DbSet<Specializare> Specializares { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentiGrupa> StudentiGrupas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CATALOG_CU_NOTE_TEMPORAR> CATALOG_CU_NOTE_TEMPORAR { get; set; }
        public virtual DbSet<CATALOG_TEMPORAR> CATALOG_TEMPORAR { get; set; }
        public virtual DbSet<NOTE_TEMPORAR> NOTE_TEMPORAR { get; set; }
        public virtual DbSet<SpecializariE> SpecializariEs { get; set; }
        public virtual DbSet<SpecializariM> SpecializariMs { get; set; }
    
        public virtual int Adaugare_Materie(Nullable<int> var_GrupaId, string var_NumeMaterie, Nullable<int> var_Profesor1ID, Nullable<int> var_Profesor2ID, Nullable<int> var_Asistent1ID, Nullable<int> var_Asistent2ID, Nullable<float> var_ProcentCurs, Nullable<float> var_ProcentLaborator, Nullable<float> var_ProcentTeme, Nullable<float> var_ProcentProiect, Nullable<bool> var_Examen, Nullable<int> var_Credite, Nullable<int> var_Sesiune)
        {
            var var_GrupaIdParameter = var_GrupaId.HasValue ?
                new ObjectParameter("Var_GrupaId", var_GrupaId) :
                new ObjectParameter("Var_GrupaId", typeof(int));
    
            var var_NumeMaterieParameter = var_NumeMaterie != null ?
                new ObjectParameter("Var_NumeMaterie", var_NumeMaterie) :
                new ObjectParameter("Var_NumeMaterie", typeof(string));
    
            var var_Profesor1IDParameter = var_Profesor1ID.HasValue ?
                new ObjectParameter("Var_Profesor1ID", var_Profesor1ID) :
                new ObjectParameter("Var_Profesor1ID", typeof(int));
    
            var var_Profesor2IDParameter = var_Profesor2ID.HasValue ?
                new ObjectParameter("Var_Profesor2ID", var_Profesor2ID) :
                new ObjectParameter("Var_Profesor2ID", typeof(int));
    
            var var_Asistent1IDParameter = var_Asistent1ID.HasValue ?
                new ObjectParameter("Var_Asistent1ID", var_Asistent1ID) :
                new ObjectParameter("Var_Asistent1ID", typeof(int));
    
            var var_Asistent2IDParameter = var_Asistent2ID.HasValue ?
                new ObjectParameter("Var_Asistent2ID", var_Asistent2ID) :
                new ObjectParameter("Var_Asistent2ID", typeof(int));
    
            var var_ProcentCursParameter = var_ProcentCurs.HasValue ?
                new ObjectParameter("Var_ProcentCurs", var_ProcentCurs) :
                new ObjectParameter("Var_ProcentCurs", typeof(float));
    
            var var_ProcentLaboratorParameter = var_ProcentLaborator.HasValue ?
                new ObjectParameter("Var_ProcentLaborator", var_ProcentLaborator) :
                new ObjectParameter("Var_ProcentLaborator", typeof(float));
    
            var var_ProcentTemeParameter = var_ProcentTeme.HasValue ?
                new ObjectParameter("Var_ProcentTeme", var_ProcentTeme) :
                new ObjectParameter("Var_ProcentTeme", typeof(float));
    
            var var_ProcentProiectParameter = var_ProcentProiect.HasValue ?
                new ObjectParameter("Var_ProcentProiect", var_ProcentProiect) :
                new ObjectParameter("Var_ProcentProiect", typeof(float));
    
            var var_ExamenParameter = var_Examen.HasValue ?
                new ObjectParameter("Var_Examen", var_Examen) :
                new ObjectParameter("Var_Examen", typeof(bool));
    
            var var_CrediteParameter = var_Credite.HasValue ?
                new ObjectParameter("Var_Credite", var_Credite) :
                new ObjectParameter("Var_Credite", typeof(int));
    
            var var_SesiuneParameter = var_Sesiune.HasValue ?
                new ObjectParameter("Var_Sesiune", var_Sesiune) :
                new ObjectParameter("Var_Sesiune", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Adaugare_Materie", var_GrupaIdParameter, var_NumeMaterieParameter, var_Profesor1IDParameter, var_Profesor2IDParameter, var_Asistent1IDParameter, var_Asistent2IDParameter, var_ProcentCursParameter, var_ProcentLaboratorParameter, var_ProcentTemeParameter, var_ProcentProiectParameter, var_ExamenParameter, var_CrediteParameter, var_SesiuneParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<usp_catalog_sesiunea_x_Result> usp_catalog_sesiunea_x(Nullable<int> id_student, Nullable<int> id_grupa, Nullable<int> semestru)
        {
            var id_studentParameter = id_student.HasValue ?
                new ObjectParameter("id_student", id_student) :
                new ObjectParameter("id_student", typeof(int));
    
            var id_grupaParameter = id_grupa.HasValue ?
                new ObjectParameter("id_grupa", id_grupa) :
                new ObjectParameter("id_grupa", typeof(int));
    
            var semestruParameter = semestru.HasValue ?
                new ObjectParameter("semestru", semestru) :
                new ObjectParameter("semestru", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_catalog_sesiunea_x_Result>("usp_catalog_sesiunea_x", id_studentParameter, id_grupaParameter, semestruParameter);
        }
    
        public virtual ObjectResult<usp_statistica_an1_Result> usp_statistica_an1(Nullable<int> id_dep, Nullable<int> id_specializare, Nullable<int> id_an)
        {
            var id_depParameter = id_dep.HasValue ?
                new ObjectParameter("id_dep", id_dep) :
                new ObjectParameter("id_dep", typeof(int));
    
            var id_specializareParameter = id_specializare.HasValue ?
                new ObjectParameter("id_specializare", id_specializare) :
                new ObjectParameter("id_specializare", typeof(int));
    
            var id_anParameter = id_an.HasValue ?
                new ObjectParameter("id_an", id_an) :
                new ObjectParameter("id_an", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_statistica_an1_Result>("usp_statistica_an1", id_depParameter, id_specializareParameter, id_anParameter);
        }
    
        public virtual ObjectResult<usp_statistica_an2_Result> usp_statistica_an2(Nullable<int> id_dep, Nullable<int> id_specializare, Nullable<int> id_an)
        {
            var id_depParameter = id_dep.HasValue ?
                new ObjectParameter("id_dep", id_dep) :
                new ObjectParameter("id_dep", typeof(int));
    
            var id_specializareParameter = id_specializare.HasValue ?
                new ObjectParameter("id_specializare", id_specializare) :
                new ObjectParameter("id_specializare", typeof(int));
    
            var id_anParameter = id_an.HasValue ?
                new ObjectParameter("id_an", id_an) :
                new ObjectParameter("id_an", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_statistica_an2_Result>("usp_statistica_an2", id_depParameter, id_specializareParameter, id_anParameter);
        }
    
        public virtual ObjectResult<usp_statistica_an3_Result> usp_statistica_an3(Nullable<int> id_dep, Nullable<int> id_specializare, Nullable<int> id_an)
        {
            var id_depParameter = id_dep.HasValue ?
                new ObjectParameter("id_dep", id_dep) :
                new ObjectParameter("id_dep", typeof(int));
    
            var id_specializareParameter = id_specializare.HasValue ?
                new ObjectParameter("id_specializare", id_specializare) :
                new ObjectParameter("id_specializare", typeof(int));
    
            var id_anParameter = id_an.HasValue ?
                new ObjectParameter("id_an", id_an) :
                new ObjectParameter("id_an", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_statistica_an3_Result>("usp_statistica_an3", id_depParameter, id_specializareParameter, id_anParameter);
        }
    
        public virtual ObjectResult<usp_statistica_an4_Result> usp_statistica_an4(Nullable<int> id_dep, Nullable<int> id_specializare, Nullable<int> id_an)
        {
            var id_depParameter = id_dep.HasValue ?
                new ObjectParameter("id_dep", id_dep) :
                new ObjectParameter("id_dep", typeof(int));
    
            var id_specializareParameter = id_specializare.HasValue ?
                new ObjectParameter("id_specializare", id_specializare) :
                new ObjectParameter("id_specializare", typeof(int));
    
            var id_anParameter = id_an.HasValue ?
                new ObjectParameter("id_an", id_an) :
                new ObjectParameter("id_an", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_statistica_an4_Result>("usp_statistica_an4", id_depParameter, id_specializareParameter, id_anParameter);
        }
    }
}
