//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Catalog_Studentesc
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTE_TEMPORAR
    {
        public int MaterieID { get; set; }
        public Nullable<int> NotaCurs { get; set; }
        public Nullable<int> NotaLaborator { get; set; }
        public Nullable<int> NotaProiect { get; set; }
        public Nullable<int> NotaFinala { get; set; }
    }
}
