//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_Catalog_Studentesc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Notas = new HashSet<Nota>();
            this.StudentiGrupas = new HashSet<StudentiGrupa>();
        }
    
        public int StudentID { get; set; }
        public string Nume { get; set; }
        public string Prenume { get; set; }
        public string CNP { get; set; }
        public int SpecializareID { get; set; }
        public int AnScolarDeInceputID { get; set; }
        public string Password { get; set; }
        public Nullable<float> Medie1 { get; set; }
        public Nullable<float> Medie2 { get; set; }
        public Nullable<float> Medie3 { get; set; }
        public Nullable<float> Medie4 { get; set; }
        public Nullable<int> Restante1 { get; set; }
        public Nullable<int> Restante2 { get; set; }
        public Nullable<int> Restante3 { get; set; }
        public Nullable<int> Restante4 { get; set; }
    
        public virtual AnScolar AnScolar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Notas { get; set; }
        public virtual Specializare Specializare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentiGrupa> StudentiGrupas { get; set; }
    }
}
