USE Catalog
GO

IF OBJECT_ID('TRG_AFTER_INSERT_NOTA') IS NOT NULL
DROP TRIGGER TRG_AFTER_INSERT_NOTA
GO

CREATE TRIGGER TRG_AFTER_INSERT_NOTA 
ON dbo.Nota	
AFTER INSERT AS
BEGIN
	DECLARE @STUDENT_ID INT;
	DECLARE @MATERIE_ID INT;
	DECLARE @GRUPA_ID INT;
	DECLARE @MEDIE1 REAL;
	DECLARE @MEDIE2 REAL;
	DECLARE @MEDIE_AN REAL;
	DECLARE @RESTANTE1 INT;
	DECLARE @RESTANTE2 INT;
	DECLARE @RESTANTET INT;
	DECLARE @AN_NOTA INT;

	SET @STUDENT_ID=(SELECT StudentID FROM INSERTED);

	SET @MATERIE_ID=(SELECT MaterieID FROM INSERTED);

	SET @GRUPA_ID=(SELECT GrupaID FROM Materie WHERE MaterieID=@MATERIE_ID);

	DECLARE @NUME nvarchar(100);
	DECLARE @PRENUME nvarchar(100);
	DECLARE @GRUPA nvarchar(100);
	

	SET @NUME=(SELECT Nume From Student where StudentID=@STUDENT_ID);
	SET @PRENUME=(SELECT Prenume From Student where StudentID=@STUDENT_ID);
	SET @GRUPA =(SELECT Nume From Grupa where @GRUPA_ID=GrupaID);

	EXEC usp_catalog_sesiunea_x @STUDENT_ID, @GRUPA_ID, 1;
	SET @MEDIE1=(SELECT AVG( CAST(NOTE_TEMPORAR.NotaFinala as FLOAT)) FROM CATALOG_TEMPORAR INNER JOIN NOTE_TEMPORAR ON CATALOG_TEMPORAR.MaterieID = NOTE_TEMPORAR.MaterieID );
	SET @RESTANTE1=( SELECT COUNT(*) FROM  CATALOG_TEMPORAR INNER JOIN NOTE_TEMPORAR ON CATALOG_TEMPORAR.MaterieID = NOTE_TEMPORAR.MaterieID WHERE NOTE_TEMPORAR.NotaFinala<5)
	


	

	EXEC usp_catalog_sesiunea_x @STUDENT_ID, @GRUPA_ID, 2;
	SET @MEDIE2= (SELECT AVG( CAST(NOTE_TEMPORAR.NotaFinala as FLOAT)) FROM CATALOG_TEMPORAR INNER JOIN NOTE_TEMPORAR ON CATALOG_TEMPORAR.MaterieID = NOTE_TEMPORAR.MaterieID );
	SET @RESTANTE2=(SELECT COUNT(*) FROM  CATALOG_TEMPORAR INNER JOIN NOTE_TEMPORAR ON CATALOG_TEMPORAR.MaterieID = NOTE_TEMPORAR.MaterieID WHERE NOTE_TEMPORAR.NotaFinala<5)

	

	
	SET @MEDIE_AN=(@MEDIE1+@MEDIE2)/2;
	

	SET @AN_NOTA=(SELECT An From Grupa WHERE GrupaID=@GRUPA_ID);

	IF  @AN_NOTA=1
	UPDATE Student SET Medie1=@MEDIE_AN  WHERE StudentID = @STUDENT_ID; 
	IF  @AN_NOTA=2
	UPDATE Student SET Medie2=@MEDIE_AN  WHERE StudentID = @STUDENT_ID; 
	IF  @AN_NOTA=3
	UPDATE Student SET Medie3=@MEDIE_AN  WHERE StudentID = @STUDENT_ID; 
	IF  @AN_NOTA=4
	UPDATE Student SET Medie4=@MEDIE_AN  WHERE StudentID = @STUDENT_ID; 

	IF  @AN_NOTA=1
	UPDATE Student SET Restante1=@RESTANTE1+@RESTANTE2  WHERE StudentID = @STUDENT_ID; 
	IF  @AN_NOTA=2
	UPDATE Student SET Restante2=@RESTANTE1+@RESTANTE2   WHERE StudentID = @STUDENT_ID; 
	IF  @AN_NOTA=3
	UPDATE Student SET Restante3=@RESTANTE1+@RESTANTE2   WHERE StudentID = @STUDENT_ID; 
	IF  @AN_NOTA=4
	UPDATE Student SET Restante4=@RESTANTE1+@RESTANTE2   WHERE StudentID = @STUDENT_ID; 

	
	PRINT @NUME;
	PRINT @PRENUME;
	PRINT @GRUPA
	PRINT 'MEDIE SEMESTRU 1';
	PRINT @MEDIE1 ;
	PRINT 'MEDIE SEMESTRU 2';
	PRINT @MEDIE2 ;
	PRINT 'MEDIE ANUALA';
	PRINT @MEDIE_AN ;
	PRINT 'NUMAR RESTANTE PRIMUL SEMESTRU';
	PRINT @RESTANTE1	;
	PRINT 'NUMAR RESTANTE AL DOILEA  SEMESTRU';
	PRINT @RESTANTE2 ;

END
GO




